// ═══════════════════════════════════════════════════════════════
// Scout Disk Compiler — Shared Styles
// ═══════════════════════════════════════════════════════════════

export const colors = {
  bg: '#0a0e17',
  surface: '#111827',
  surfaceAlt: '#1a2236',
  border: '#1e293b',
  borderFocus: '#3b82f6',
  text: '#e2e8f0',
  textDim: '#94a3b8',
  textMuted: '#64748b',
  accent: '#3b82f6',
  accentHover: '#2563eb',
  success: '#10b981',
  successBg: 'rgba(16,185,129,0.1)',
  error: '#ef4444',
  errorBg: 'rgba(239,68,68,0.1)',
  warning: '#f59e0b',
  warningBg: 'rgba(245,158,11,0.1)',
  purple: '#8b5cf6',
  purpleBg: 'rgba(139,92,246,0.1)',
  cyan: '#06b6d4',
  cyanBg: 'rgba(6,182,212,0.1)',
};

export const base: Record<string, React.CSSProperties> = {
  app: {
    minHeight: '100vh',
    backgroundColor: colors.bg,
    color: colors.text,
    fontFamily: "'Amazon Ember', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
    fontSize: '14px',
  },
  header: {
    padding: '16px 24px',
    borderBottom: `1px solid ${colors.border}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    background: `linear-gradient(135deg, ${colors.surface} 0%, ${colors.surfaceAlt} 100%)`,
  },
  headerTitle: {
    fontSize: '18px',
    fontWeight: 700,
    margin: 0,
    color: colors.text,
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
  },
  tabBar: {
    display: 'flex',
    gap: '0',
    borderBottom: `1px solid ${colors.border}`,
    backgroundColor: colors.surface,
    padding: '0 24px',
  },
  tab: {
    padding: '12px 24px',
    cursor: 'pointer',
    border: 'none',
    background: 'none',
    color: colors.textDim,
    fontSize: '13px',
    fontWeight: 600,
    borderBottom: '2px solid transparent',
    transition: 'all 0.15s',
    fontFamily: 'inherit',
  },
  tabActive: {
    color: colors.accent,
    borderBottomColor: colors.accent,
  },
  content: {
    padding: '24px',
    maxWidth: '1200px',
    margin: '0 auto',
  },
  card: {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: '8px',
    padding: '20px',
    marginBottom: '16px',
  },
  cardTitle: {
    fontSize: '14px',
    fontWeight: 700,
    marginBottom: '16px',
    color: colors.text,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  label: {
    display: 'block',
    fontSize: '12px',
    fontWeight: 600,
    color: colors.textDim,
    marginBottom: '4px',
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  input: {
    width: '100%',
    padding: '8px 12px',
    backgroundColor: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    color: colors.text,
    fontSize: '13px',
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box' as const,
  },
  select: {
    width: '100%',
    padding: '8px 12px',
    backgroundColor: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    color: colors.text,
    fontSize: '13px',
    fontFamily: 'inherit',
    outline: 'none',
    boxSizing: 'border-box' as const,
    cursor: 'pointer',
  },
  textarea: {
    width: '100%',
    padding: '8px 12px',
    backgroundColor: colors.surfaceAlt,
    border: `1px solid ${colors.border}`,
    borderRadius: '6px',
    color: colors.text,
    fontSize: '13px',
    fontFamily: "'Amazon Ember Mono', monospace",
    outline: 'none',
    boxSizing: 'border-box' as const,
    resize: 'vertical' as const,
    minHeight: '80px',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '12px',
  },
  row3: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr',
    gap: '12px',
  },
  row4: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr 1fr 1fr',
    gap: '12px',
  },
  field: {
    marginBottom: '12px',
  },
  btn: {
    padding: '10px 20px',
    borderRadius: '6px',
    border: 'none',
    cursor: 'pointer',
    fontSize: '13px',
    fontWeight: 600,
    fontFamily: 'inherit',
    transition: 'all 0.15s',
  },
  btnPrimary: {
    backgroundColor: colors.accent,
    color: '#fff',
  },
  btnSuccess: {
    backgroundColor: colors.success,
    color: '#fff',
  },
  btnDanger: {
    backgroundColor: colors.error,
    color: '#fff',
  },
  badge: {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '11px',
    fontWeight: 700,
    textTransform: 'uppercase' as const,
    letterSpacing: '0.5px',
  },
  mono: {
    fontFamily: "'Amazon Ember Mono', monospace",
    fontSize: '12px',
  },
};
